### ISSUE TITLE
Add --output option to save CSV data directly to a file

### ISSUE THREAD

**Issue by lucas0maia** [flother/htmltab#4]
Hello. Thanks for the script, it seems to work perfectly even with LARGE files.

However, the script displays the CSV in the terminal but does not save a CSV. How can I save a csv file with the result?

Thanks.

**Comment by flother** [comment]
Hi Lucas,

Thanks for the kind words. The program's designed to output to [`stdout`](https://www.computerhope.com/jargon/s/stdout.htm) so you can save the CSV to any file you want. This should work on Linux, MacOS, and Windows:

```sh
htmltab --select 1 example.html > your_file.csv
```

That will pick the first table in the local file `example.html` and save the result to `your_file.csv` in the current directory. If you're on a Unix-like system (Linux, MacOS) you can use the output in a [pipeline](https://en.wikipedia.org/wiki/Pipeline_%28Unix%29) too.

Having said that, I think I'd like to add an `--output` option to `htmltab`, so that you could save to a file like this:

```sh
htmltab --select 1 example.html --output your_file.csv
```

I'll leave this issue open as a reminder for me to add that.
